CREATE TABLE IF NOT EXISTS RESOLVEDB.T_USER
(
    id    BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    name  VARCHAR(255)                      NOT NULL,
    email VARCHAR(255)                      NOT NULL
);
